### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by michaelamponsah** [michaelamponsah/project-catalog#34]
### Kindly find below the various tasks with the respective assignees for this project

- [x] @michaelamponsah  has been assigned to tasks listed for `Team member #1`

- [x] @willy836   has been assigned to tasks listed for `Team member #2`

- [x] @oguntayomicheal   has been assigned to tasks listed for `Team member #3`

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @michaelamponsah, @willy836 and @oguntayomicheal,

Good job so far!
✔️ Kanban columns are complete
✔️ Assignment of tasks
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] You have some tasks with the "Description to be added" text. Kindly add the actual descriptions.

  Some have no descriptions at all.

  vague description | no description
  :---:|:---:
  ![image](https://user-images.githubusercontent.com/36542986/226312005-029c83cb-cd76-40c2-a78d-ffddb30ea86e.png) |    ![image](https://user-images.githubusercontent.com/36542986/226313172-3d18c096-eca1-4b25-9edc-bbbd6093a2d5.png)

- [ ] Team member 1 is missing cards for these tasks. Kindly create them.

  ![image](https://user-images.githubusercontent.com/36542986/226312831-c000d30a-9091-4889-9d98-3297ef26509c.png)

- [ ] Team member 3 is missing a corresponding card for this task.

  ![image](https://user-images.githubusercontent.com/36542986/226314047-8edc0b06-c889-4bb0-9428-267b6f29ed27.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @michaelamponsah, @willy836 and @oguntayomicheal,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] As pointed out by the previous reviewer ALL your tasks should have appropriate descriptions. Some of your tasks still have the text pointed out previously and some do not have a description at all

  1 | 2
  :---:|:---:
  ![ururd](https://user-images.githubusercontent.com/81468675/226325801-0d1ab47d-27c9-4220-9d60-1bceaa4ad520.jpg) | ![ife](https://user-images.githubusercontent.com/81468675/226325812-6488efcc-43dc-4e9c-a8cb-f171e3194e65.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michaelamponsah** [comment]
#### @julie-ify, while you've done an excellent job reviewing our work, you're missing some points here. Some of the tasks in the Kanban board are self-descriptive. As such, there is no need to add descriptions for such tasks.
#### We would appreciate it if you take this into consideration during reviews.

#### Thanks ☺️.
